server:
  port: 8000
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: API gateway Global filter
            preLogger: true
            postLogger: true
      routes:
        - id: first
          uri: lb://FIRST-APP
          predicates:
            - Path=/first-service/**
          filters:
            - CustomFilter
        - id: second
          uri: lb://SECOND-APP
          predicates:
            - Path=/second-service/**
          filters:
            - name: CustomFilter
            - name: LoggingFilter
              args:
                baseMessage: API gateway logging filter
                preLogger: true
                postLogger: true